services:
  vantelia:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: vantelia-app
    restart: unless-stopped
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    volumes:
      - ../../data:/app/data
      - ../../storage:/app/storage
      - ../../config.json:/app/config.json
      - ../../secrets:/app/secrets
